### PR TITLE
2 cleaning up and syncing with py lib

### PR DESCRIPTION
**Pull request by vitorbaptista**
This is ready for review :+1:

### CODE REVIEW

**Comment by pwalsh** [comment]
Hey @vitorbaptista sorry for **long** delay on this :).

I did not think if this before, but part of the bloat is that we are including isomorphic-fetch and bluebird (or other promise lib) in our browser builds.

Is there a clean way that we could still use these as normal in the source, but ensure that the browser builds never bundle them? Then the instructions for users are that they need a browser with `Promise` and `Fetch`, or, they need to add a polyfill.

Putting aside the CSV parsing issue we've talked about, would this help with the bloat concerns for the lib?

**Comment by vitorbaptista** [comment]
For Promise it's easy (as our NodeJS version already has Promises), for fetch it's a bit more tricky because NodeJS doesn't support it natively, so we would need a way to load `isomorphic-fetch` or `node-fetch` while on Node, but not bundle it for the browser.

That sounds like the way to go.

**Comment by rufuspollock** [comment]
@pwalsh can this merge?

**Comment by pwalsh** [comment]
@rgrp yes. can you merge and publish? I was just holding to more deeply investigate pathways to reduce bloat in browser distributions of our core libs.

**Pull request merged**
